GET http://localhost:3001/api/product HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQzYjI3MzhjLTQxN2EtNGM2MC1hMzBlLTMyZGE1Yzk2ZmVjZCIsInVzZXJuYW1lIjoiYW5keXN3YW5lcG9lbCIsImlhdCI6MTY4NzYxNDk0MX0.xiEgLNW4Lo-dDCie3sVVvgiRUsPUQT8ftMkmYh_GEZk
###


POST http://localhost:3001/api/product HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQzYjI3MzhjLTQxN2EtNGM2MC1hMzBlLTMyZGE1Yzk2ZmVjZCIsInVzZXJuYW1lIjoiYW5keXN3YW5lcG9lbCIsImlhdCI6MTY4NzYxNDk0MX0.xiEgLNW4Lo-dDCie3sVVvgiRUsPUQT8ftMkmYh_GEZk

{
    "name": "dgdgfdgdfgdfgfdgfddgdgfdgdfgdfgfdgfddgdgfdgdfgdfgfdgfddgdgfdgdfgdfgfdgfddgdgfdgdfgdfgfdgfddgdgfdgdfgdfgfdgfddgdgfdgdfgdfgfdgfddgdgfdgdfgdfgfdgfddgdgfdgdfgdfgfdgfddgdgfdgdfgdfgfdgfddgdgfdgdfgdfgfdgfddgdgfdgdfgdfgfdgfddgdgfdgdfgdfgfdgfddgdgfdgdfgdfgfdgfddgdgfdgdfgdfgfdgfddgdgfdgdfgdfgfdgfddgdgfdgdfgdfgfdgfddgdgfdgdfgdfgfdgfddgdgfdgdfgdfgfdgfddgdgfdgdfgdfgfdgfddgdgfdgdfgdfgfdgfddgdgfdgdfgdfgfdgfddgdgfdgdfgdfgfdgfddgdgfdgdfgdfgfdgfddgdgfdgdfgdfgfdgfddgdgfdgdfgdfgfdgfddgdgfdgdfgdfgfdgfddgdgfdgdfgdfgfdgfddgdgfdgdfgdfgfdgfddgdgfdgdfgdfgfdgfddgdgfdgdfgdfgfdgfddgdgfdgdfgdfgfdgfddgdgfdgdfgdfgfdgfddgdgfdgdfgdfgfdgfddgdgfdgdfgdfgfdgfddgdgfdgdfgdfgfdgfddgdgfdgdfgdfgfdgfddgdgfdgdfgdfgfdgfddgdgfdgdfgdfgfdgfddgdgfdgdfgdfgfdgfddgdgfdgdfgdfgfdgfddgdgfdgdfgdfgfdgfddgdgfdgdfgdfgfdgfddgdgfdgdfgdfgfdgfddgdgfdgdfgdfgfdgfddgdgfdgdfgdfgfdgfddgdgfdgdfgdfgfdgfddgdgfdgdfgdfgfdgfddgdgfdgdfgdfgfdgfddgdgfdgdfgdfgfdgfddgdgfdgdfgdfgfdgfddgdgfdgdfgdfgfdgfddgdgfdgdfgdfgfdgfddgdgfdgdfgdfgfdgfd"
}
###


DELETE http://localhost:3001/api/product/43ff1edd-2d7b-4fb2-8b74-ffdbd5a28a12 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQzYjI3MzhjLTQxN2EtNGM2MC1hMzBlLTMyZGE1Yzk2ZmVjZCIsInVzZXJuYW1lIjoiYW5keXN3YW5lcG9lbCIsImlhdCI6MTY4NzYxNDk0MX0.xiEgLNW4Lo-dDCie3sVVvgiRUsPUQT8ftMkmYh_GEZk

###
